### ISSUE TITLE
Question: what is `nonbonded.library.models.targets.EvaluatorTarget.data_set_ids`

### ISSUE THREAD

**Issue by lilyminium** [openforcefield/openff-sage#6]
As seen in: https://github.com/openforcefield/openff-sage/blob/325460b254c3532b96ae43deb5a3a963605609b6/scripts/setup-vdw-v1.py#L87

Is this an identifier for pulling down data from QCArchive, or just for record-keeping? I wonder if this might have something to do with https://github.com/SimonBoothroyd/nonbonded/issues/94.

**Comment by SimonBoothroyd** [comment]
In principle this pull from the RESTFul API I have, but it also corresponds to the id stored in the [dataset in this repo](https://github.com/openforcefield/openff-sage/blob/main/data-set-curation/physical-property/optimizations/data-sets/sage-train-v1.json). In the next `nonbonded` release you will be able to generate the optimization inputs from a local copy of the dataset, using this id to match, rather than needing to pull a remote one.
